LOAD DATA LOCAL INFILE 'faculty.csv' INTO TABLE faculty FIELDS TERMINATED BY "," ENCLOSED BY "'" LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'teacher.csv' INTO TABLE teacher FIELDS TERMINATED BY "," ENCLOSED BY "'" LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'department.csv' INTO TABLE department FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'program.csv' INTO TABLE program FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'course.csv' INTO TABLE course FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/home/wulios/Downloads/tempcsv/course_slot.csv' INTO TABLE course_slot FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE '/home/wulios/Downloads/tempcsv/course_list.csv' INTO TABLE course_list FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
